version: "3.1"

services:
  note-service:
    image: notes-service:v1
    restart: always
    ports:
      - "8001:8080"
    networks:
      - springboot
    depends_on:
      - mongodb
      - mongo-express

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    restart: always
    networks:
      - springboot
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - springboot
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo: { }

networks:
  springboot: