spring:
  application:
    name: service-notes

  data:
    mongodb:
      database: block_notes
      username: admin
      password: password
      port: 27017
      host: mongodb
      authentication-database: admin

springdoc:
  swagger-ui:
    enabled: true
    path: /openapi/ui
  api-docs:
    enabled: true
    path: /openapi/docs

