spring:
  application:
    name: service-notes

  data:
    mongodb:
      database: block_notes
      #connection to MongoDB Atlas
      uri: mongodb+srv://user:Iy4EcRKBVjJQ7BiA@testone.ikp6lbv.mongodb.net/?retryWrites=true&w=majority

