spring:
  application:
    name: service-notes

  data:
    mongodb:
      database: block_notes
      username: admin
      password: password
      port: 27017
      host: localhost
      authentication-database: admin

